// Authentication and authorization constants

export const USER_ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  HR_ADMIN: "HR_ADMIN",
  HR_MANAGER: "HR_MANAGER",
  MANAGER: "MANAGER",
  EMPLOYEE: "EMPLOYEE",
  READONLY: "READONLY",
} as const;

export const PERMISSIONS = {
  // Employee permissions
  EMPLOYEE_CREATE: "employee:create",
  EMPLOYEE_READ: "employee:read",
  EMPLOYEE_UPDATE: "employee:update",
  EMPLOYEE_DELETE: "employee:delete",
  EMPLOYEE_READ_ALL: "employee:read:all",
  EMPLOYEE_UPDATE_SALARY: "employee:update:salary",

  // Department permissions
  DEPARTMENT_CREATE: "department:create",
  DEPARTMENT_READ: "department:read",
  DEPARTMENT_UPDATE: "department:update",
  DEPARTMENT_DELETE: "department:delete",

  // Leave permissions
  LEAVE_CREATE: "leave:create",
  LEAVE_READ: "leave:read",
  LEAVE_UPDATE: "leave:update",
  LEAVE_DELETE: "leave:delete",
  LEAVE_APPROVE: "leave:approve",
  LEAVE_READ_ALL: "leave:read:all",

  // Payroll permissions
  PAYROLL_CREATE: "payroll:create",
  PAYROLL_READ: "payroll:read",
  PAYROLL_UPDATE: "payroll:update",
  PAYROLL_DELETE: "payroll:delete",
  PAYROLL_PROCESS: "payroll:process",

  // Recruitment permissions
  RECRUITMENT_CREATE: "recruitment:create",
  RECRUITMENT_READ: "recruitment:read",
  RECRUITMENT_UPDATE: "recruitment:update",
  RECRUITMENT_DELETE: "recruitment:delete",
  RECRUITMENT_SCHEDULE_INTERVIEW: "recruitment:schedule:interview",

  // Reports permissions
  REPORTS_EMPLOYEE: "reports:employee",
  REPORTS_LEAVE: "reports:leave",
  REPORTS_PAYROLL: "reports:payroll",
  REPORTS_RECRUITMENT: "reports:recruitment",

  // System permissions
  SYSTEM_ADMIN: "system:admin",
  USER_MANAGEMENT: "user:management",
} as const;

export const ROLE_PERMISSIONS = {
  [USER_ROLES.SUPER_ADMIN]: [...Object.values(PERMISSIONS)],

  [USER_ROLES.HR_ADMIN]: [
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_DELETE,
    PERMISSIONS.EMPLOYEE_READ_ALL,
    PERMISSIONS.EMPLOYEE_UPDATE_SALARY,
    PERMISSIONS.DEPARTMENT_CREATE,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.DEPARTMENT_UPDATE,
    PERMISSIONS.DEPARTMENT_DELETE,
    PERMISSIONS.LEAVE_READ_ALL,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.PAYROLL_CREATE,
    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_UPDATE,
    PERMISSIONS.PAYROLL_PROCESS,
    PERMISSIONS.RECRUITMENT_CREATE,
    PERMISSIONS.RECRUITMENT_READ,
    PERMISSIONS.RECRUITMENT_UPDATE,
    PERMISSIONS.RECRUITMENT_DELETE,
    PERMISSIONS.RECRUITMENT_SCHEDULE_INTERVIEW,
    ...Object.values(PERMISSIONS).filter((p) => p.startsWith("reports:")),
  ],

  [USER_ROLES.HR_MANAGER]: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_READ_ALL,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.LEAVE_READ_ALL,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.RECRUITMENT_READ,
    PERMISSIONS.RECRUITMENT_UPDATE,
    PERMISSIONS.RECRUITMENT_SCHEDULE_INTERVIEW,
    PERMISSIONS.REPORTS_EMPLOYEE,
    PERMISSIONS.REPORTS_LEAVE,
    PERMISSIONS.REPORTS_RECRUITMENT,
  ],

  [USER_ROLES.MANAGER]: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.REPORTS_EMPLOYEE,
    PERMISSIONS.REPORTS_LEAVE,
  ],

  [USER_ROLES.EMPLOYEE]: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_UPDATE,
  ],

  [USER_ROLES.READONLY]: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.RECRUITMENT_READ,
  ],
} as const;

export const JWT_CONFIG = {
  ACCESS_TOKEN_EXPIRY: "15m",
  REFRESH_TOKEN_EXPIRY: "7d",
  PASSWORD_RESET_EXPIRY: "1h",
  EMAIL_VERIFICATION_EXPIRY: "24h",
} as const;

export const PASSWORD_CONFIG = {
  MIN_LENGTH: 8,
  REQUIRE_UPPERCASE: true,
  REQUIRE_LOWERCASE: true,
  REQUIRE_NUMBERS: true,
  REQUIRE_SPECIAL_CHARS: true,
  MAX_FAILED_ATTEMPTS: 5,
  LOCKOUT_DURATION: 30 * 60 * 1000, // 30 minutes
} as const;

export const SESSION_CONFIG = {
  COOKIE_NAME: "hrm_session",
  COOKIE_MAX_AGE: 7 * 24 * 60 * 60 * 1000, // 7 days
  COOKIE_SECURE: process.env.NODE_ENV === "production",
  COOKIE_HTTP_ONLY: true,
  COOKIE_SAME_SITE: "strict" as const,
} as const;
